#ifndef SRC_TRABALHOBASEDEFENSE_LOGLEVEL_H
#define SRC_TRABALHOBASEDEFENSE_LOGLEVEL_H

enum LogLevel {
    INFO,
    WARNING,
    ERROR,
    DEBUG,
    CRITICAL
};

#endif //SRC_TRABALHOBASEDEFENSE_LOGLEVEL_H
