name: test_build
on: [push]
jobs:
  test_build:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
      - name: Set up cmake
      - run: apt-get install -y cmake
      - name: Set up build directory
      - run: mkdir build && cd build
      - name: Build
      - run: cmake ..
      - name: Make
      - run: make